# Generated by Django 4.0.4 on 2023-09-04 21:27

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de operación')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('estatus', models.IntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Fecha de operación',
                'verbose_name_plural': 'Fechas de operación',
                'db_table': 'FechaOperacion',
                'ordering': ['-fecha'],
                'permissions': (('cocina', 'Cocina consulta'), ('cocina_termina', 'Cocina termina'), ('cocina_cancela', 'Cocina cancela'), ('bar', 'Bar consulta'), ('bar_termina', 'Bar termina'), ('bar_cancela', 'Bar cancela'), ('servicio', 'Comandas consulta'), ('servicio_nueva', 'Comanda nueva'), ('servicio_solicitar', 'Comanda solicita'), ('servicio_cancelar', 'Comanda cancela'), ('servicio_pagar', 'Comanda paga'), ('servicio_ver', 'Comanda detalle'), ('servicio_cierra', 'Comanda cierra'), ('entregas', 'Entregas consulta'), ('entregas_ok', 'Entrega OK'), ('entregas_cancela', 'Entrega cancelada'), ('reasignar', 'Reasignar'), ('consultas_seguimiento', 'Consulta de seguimiento'), ('consultas_reporte_dia', 'Consulta de reporte del día'), ('catalogo', 'Catálogo consulta'), ('catalogo_agregar', 'Catálogo Agrega'), ('catalogo_modificar', 'Catáogo Modifica'), ('accesos', 'Accesos consulta'), ('accesos_modificar', 'Accesos modifica'), ('abrir', 'Día abre'), ('cerrar', 'Día cierra'), ('usuarios', 'Usuarios consulta'), ('crea_usuario', 'Usuario nuevo'), ('modifica_usuario', 'Usuario modifica')),
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
