# Generated by Django 4.0.4 on 2023-05-28 23:17

import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de operación')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('estatus', models.IntegerField(choices=[(0, 'Cerrado'), (1, 'Abierto')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Fecha de operación',
                'verbose_name_plural': 'Fechas de operación',
                'db_table': 'FechaOperacion',
                'ordering': ['-fecha'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
