# Generated by Django 4.0.4 on 2023-09-04 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contable',
            name='usuario_abre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioContaleAbre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contable',
            name='usuario_cierra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioContableCierra', to=settings.AUTH_USER_MODEL),
        ),
    ]
