# Generated by Django 4.0.4 on 2023-06-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contable',
            options={'ordering': ['-fecha'], 'permissions': (('cocina', 'Consulta cocina'), ('cocina_termina', 'Cocina termina'), ('cocina_cancela', 'Cocina cancela'), ('bar', 'Consulta bar'), ('bar_termina', 'Bar termina'), ('bar_cancela', 'Bar cancela'), ('servicio', 'Consulta comandas'), ('servicio_nueva', 'Nueva comanda'), ('servicio_solicitar', 'Solicita a comanda'), ('servicio_cancelar', 'Comanda cancela'), ('servicio_pagar', 'Comanda paga'), ('servicio_ver', 'Comanda consulta'), ('servicio_cierra', 'Comanda cierra'), ('entregas', 'Consulta entregas'), ('entregas_ok', 'Comanda entrega'), ('entregas_cancela', 'Comanda cancelada'), ('reasignar', 'Reasignar'), ('consultas_seguimiento', 'Consulta de seguimiento'), ('consultas_reporte_dia', 'Consulta de reporte del día'), ('catalogo', 'Consulta catálogo'), ('catalogo_agregar', 'Agrega catálogo'), ('catalogo_modificar', 'Modifica catálogo'), ('accesos', 'Consulta accesos'), ('accesos_modificar', 'Modifica accesos'), ('abrir', 'Abre día'), ('cerrar', 'Cierra día')), 'verbose_name': 'Fecha de operación', 'verbose_name_plural': 'Fechas de operación'},
        ),
    ]
