# Generated by Django 4.0.4 on 2023-09-04 21:27

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Promoción')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('tipo', models.IntegerField(choices=[(1, 'Combo'), (2, 'Promoción')], default=1, verbose_name='Tipo')),
                ('componentes', models.JSONField(blank=True, null=True, verbose_name='Componentes')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('imagen', models.IntegerField(blank=True, null=True, verbose_name='Imagen paq.')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'Paquete',
                'ordering': ['tipo', 'nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('breve', models.CharField(blank=True, max_length=255, null=True, verbose_name='Breve descripción')),
                ('tipo', models.IntegerField(choices=[(1, 'Cocina'), (2, 'Bar')], default=1, verbose_name='Tipo')),
                ('insumos', models.JSONField(blank=True, null=True, verbose_name='Ingredientes')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('imagen', models.IntegerField(blank=True, null=True, verbose_name='Imagen prod.')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('imagen', models.IntegerField(blank=True, null=True, verbose_name='Imagen insumo.')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo_grupo', to='producto.grupo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'Insumo',
                'ordering': ['grupo', 'nombre'],
                'unique_together': {('grupo', 'nombre')},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
