# Generated by Django 4.0.4 on 2023-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
