# Generated by Django 4.0.4 on 2023-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente'),
        ),
    ]
