# Generated by Django 4.0.4 on 2023-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cliente'),
        ),
    ]
