# Generated by Django 4.0.4 on 2023-06-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cliente',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cliente'),
        ),
    ]
