# Generated by Django 4.0.4 on 2023-10-20 00:34

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0008_alter_caja_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0, verbose_name='Tablas cliente')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'db_table': 'Sorteo',
                'ordering': ['id'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(verbose_name='Número 24')),
                ('sal1', models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 24')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clienteTabla', to='loteria.cliente')),
            ],
            options={
                'verbose_name': 'Tabla',
                'verbose_name_plural': 'Tablas',
                'db_table': 'Tabla',
                'ordering': ['id'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Cliente_comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Tablas cliente')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteCliente', to='loteria.cliente')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandaCliente', to='pedido.comanda')),
            ],
            options={
                'verbose_name': 'Cliente comanda',
                'verbose_name_plural': 'Cliente comandas',
                'db_table': 'ClienteComanda',
                'ordering': [('cliente', 'comanda')],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
