# Generated by Django 4.0.4 on 2023-10-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0002_sorteo_leido_alter_sorteo_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente_comanda',
            options={'ordering': ['cliente_id', 'comanda_id'], 'verbose_name': 'Cliente comanda', 'verbose_name_plural': 'Cliente comandas'},
        ),
        migrations.AddField(
            model_name='tabla',
            name='num10',
            field=models.IntegerField(default=0, verbose_name='Número 10'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num11',
            field=models.IntegerField(default=0, verbose_name='Número 11'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num12',
            field=models.IntegerField(default=0, verbose_name='Número 12'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num13',
            field=models.IntegerField(default=0, verbose_name='Número 13'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num14',
            field=models.IntegerField(default=0, verbose_name='Número 14'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num15',
            field=models.IntegerField(default=0, verbose_name='Número 15'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num16',
            field=models.IntegerField(default=0, verbose_name='Número 16'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num17',
            field=models.IntegerField(default=0, verbose_name='Número 17'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num18',
            field=models.IntegerField(default=0, verbose_name='Número 18'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num19',
            field=models.IntegerField(default=0, verbose_name='Número 19'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num2',
            field=models.IntegerField(default=0, verbose_name='Número 2'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num20',
            field=models.IntegerField(default=0, verbose_name='Número 20'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num21',
            field=models.IntegerField(default=0, verbose_name='Número 21'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num22',
            field=models.IntegerField(default=0, verbose_name='Número 22'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num23',
            field=models.IntegerField(default=0, verbose_name='Número 23'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num24',
            field=models.IntegerField(default=0, verbose_name='Número 24'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num3',
            field=models.IntegerField(default=0, verbose_name='Número 3'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num4',
            field=models.IntegerField(default=0, verbose_name='Número 4'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num5',
            field=models.IntegerField(default=0, verbose_name='Número 5'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num6',
            field=models.IntegerField(default=0, verbose_name='Número 6'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num7',
            field=models.IntegerField(default=0, verbose_name='Número 7'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num8',
            field=models.IntegerField(default=0, verbose_name='Número 8'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='num9',
            field=models.IntegerField(default=0, verbose_name='Número 9'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal10',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 10'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal11',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 11'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal12',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 12'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal13',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 13'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal14',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 14'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal15',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 15'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal16',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 16'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal17',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 17'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal18',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 18'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal19',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 19'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal2',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 2'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal20',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 20'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal21',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 21'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal22',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 22'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal23',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 23'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal24',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 24'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal3',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 3'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal4',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 4'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal5',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 5'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal6',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 6'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal7',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 7'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal8',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 8'),
        ),
        migrations.AddField(
            model_name='tabla',
            name='sal9',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 9'),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='num1',
            field=models.IntegerField(default=0, verbose_name='Número 1'),
        ),
        migrations.AlterField(
            model_name='tabla',
            name='sal1',
            field=models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Salió 1'),
        ),
    ]
