# Generated by Django 4.0.4 on 2023-10-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0003_alter_cliente_comanda_options_tabla_num10_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabla',
            new_name='Tabla_bingo',
        ),
    ]
