# Generated by Django 4.0.4 on 2023-10-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0004_rename_tabla_tabla_bingo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tabla_bingo',
            table='Tabla_bingo',
        ),
    ]
