# Generated by Django 4.0.4 on 2023-10-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loteria', '0005_alter_tabla_bingo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_bingo',
            name='tabla_numero',
            field=models.IntegerField(default=0, verbose_name='Número de tabla'),
        ),
    ]
