# Generated by Django 4.0.4 on 2023-05-28 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='usuario_cancela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalleCancela', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='usuario_cobra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalleCobra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='usuario_elabora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalleElabora', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='usuario_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalleEntrega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalle',
            name='usuario_reasigna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioDetalleReasigna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioComanda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='usuario_cancela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioComandaCancela', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comanda',
            name='usuario_cierra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioComandaCierre', to=settings.AUTH_USER_MODEL),
        ),
    ]
