# Generated by Django 4.2.5 on 2023-09-13 01:31

from django.db import migrations, models
import pedido.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='fecha_contable',
            field=models.DateField(default=pedido.models.default_fecha_contable, verbose_name='Fecha Contable'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='fecha_contable',
            field=models.DateField(default=pedido.models.default_fecha_contable, verbose_name='Fecha Contable'),
        ),
    ]
