# Generated by Django 4.2.5 on 2023-09-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_caja_fecha_contable_detalle_fecha_contable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comanda',
            unique_together={('mesa', 'fecha_contable')},
        ),
    ]
