# Generated by Django 4.0.4 on 2023-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_comanda_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='mesa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesa'),
        ),
    ]
