# Generated by Django 4.2.5 on 2023-09-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_comanda_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='especifico',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
