# Generated by Django 4.2.5 on 2023-09-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_caja_especifico_alter_caja_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='nom_paquete',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paquete'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='nom_producto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto'),
        ),
    ]
