# Generated by Django 4.0.4 on 2023-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_detalle_especifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Por pagar'), (2, 'Pagado')], default=1, verbose_name='Estatus'),
        ),
    ]
