# Generated by Django 4.0.4 on 2023-10-27 13:29

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_caja_importe_efectivo_caja_importe_tarjeta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('importe_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('importe_tranferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['-fecha_alta'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.RemoveField(
            model_name='caja',
            name='importe_efectivo',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='importe_tarjeta',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='importe_tranferencia',
        ),
        migrations.CreateModel(
            name='CajaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.caja')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pago')),
            ],
            options={
                'verbose_name': 'Pago caja',
                'verbose_name_plural': 'Pagos por caja',
                'db_table': 'CajaPago',
                'ordering': ['caja', 'pago'],
            },
        ),
    ]
