# Generated by Django 4.0.4 on 2023-10-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_pago_remove_caja_importe_efectivo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='importe_tranferencia',
            new_name='importe_transferencia',
        ),
    ]
