# Generated by Django 4.0.4 on 2023-10-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_rename_importe_tranferencia_pago_importe_transferencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CajaPago',
        ),
    ]
