# Generated by Django 4.0.4 on 2023-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_delete_cajapago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='caja',
            field=models.ManyToManyField(to='pedido.caja'),
        ),
    ]
