# Generated by Django 4.0.4 on 2023-10-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_pago_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='caja',
        ),
    ]
