# Generated by Django 4.0.4 on 2023-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_remove_pago_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='pago',
            field=models.ManyToManyField(to='pedido.pago'),
        ),
    ]
